export const ELECTRIC_TYPE = [
  {
    title: "400KW交流同步发电机",
    content: "xx公司",
    img: "电机6.jpg",
    type: "电机",
    time: "2024",
  },
  {
    title: "280KW交流电机",
    content: "xx公司",
    img: "电机7.jpg",
    type: "电机",
    time: "2024",
  },
  {
    title: "300KW同步发电机",
    content: "xx公司",
    img: "电机2.jpg",
    type: "电机",
    time: "2024",
  },
  {
    title: "300KW发电机",
    content: "xx公司",
    img: "电机3.jpg",
    type: "电机",
    time: "2023",
  },
  {
    title: "30KW交流水泵电机",
    content: "xx公司",
    img: "电机5.jpg",
    type: "电机",
    time: "2024",
  },
  {
    title: "500kVA变压器",
    content: "xx公司",
    img: "变压器1.jpg",
    type: "变压器",
    time: "2024",
  },
  {
    title: "1000kVA变压器",
    content: "xx公司",
    img: "变压器2.jpg",
    type: "变压器",
    time: "2024",
  },
  {
    title: "800kVA变压器",
    content: "xx公司",
    img: "变压器3.jpg",
    type: "变压器",
    time: "2024",
  },
  {
    title: "600kVA变压器",
    content: "xx公司",
    img: "变压器4.jpg",
    type: "变压器",
    time: "2024",
  },
  {
    title: "600kVA变压器",
    content: "xx公司",
    img: "变压器5.jpg",
    type: "变压器",
    time: "2024",
  },
  {
    title: "控制电路",
    content: "xx公司，使用了10年",
    img: "控制柜1.jpg",
    type: "控制线路",
    time: "2024",
  },
  {
    title: "控制电路",
    content: "xx公司，使用了10年",
    img: "控制柜2.jpg",
    type: "控制线路",
    time: "2024",
  },
  {
    title: "控制电路",
    content: "xx公司，使用了10年",
    img: "控制柜3.jpg",
    type: "控制线路",
    time: "2024",
  },
  {
    title: "控制电路",
    content: "xx公司，使用了10年",
    img: "控制柜4.jpg",
    type: "控制线路",
    time: "2024",
  },
  // {
  //   title: "控制电路",
  //   content: "xx公司，使用了10年",
  //   img: "控制柜5.jpg",
  //   type: "控制线路",
  //   time: "2024",
  // },
  {
    title: "控制电路",
    content: "xx公司，使用了10年",
    img: "控制柜6.jpg",
    type: "控制线路",
    time: "2024",
  },
];

// [
//   "电机",
//   "直流电机",
//   "变压器",
//   "控制线路设计安装",
//   "水泵",
//   "工业电器设计安装",
// ];
